name: leilao
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Dependência para enviar emails
  mailer: ^5.1.4

  # Dependência para testes de integração
  integration_test:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Pacote para simulação e testes de objetos (mock)
  mockito: ^5.0.15
  mysql1: ^0.19.2
  # Conjunto de lints recomendado para boas práticas
  flutter_lints: ^2.0.0

  # Dependência para realizar testes de integração
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true